CREATE TABLE comments (
  id INTEGER AUTO_INCREMENT PRIMARY KEY,
  content VARCHAR(2048),
  post_id INTEGER,
  created_at TIMESTAMP,
  FOREIGN KEY (post_id) REFERENCES posts (id) ON UPDATE CASCADE ON DELETE CASCADE
);